### ISSUE TITLE
mavenplugin project Cannot invoke "String.toCharArray()" because "<parameter1>" is null

### ISSUE THREAD

**Issue by xhc-code** [FasterXML/jackson-dataformats-text#385] opened 2023-02-18 06:45 UTC
```xm
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.10.5</version>
</dependency>
```
When writing the maven plugin, introduce the jackson-dataformat-yaml dependency, The "Cannot invoke "String.toCharArray()" because "<parameter1>" is null" exception error occurs above 2.10.5(included).
It is available under version 2.10.5(not included).

2.9.10 Version can be used normally and no error is reported.
Versions between 2.10.5 and 2.14.2 have been tested and Cannot be used normally. An error message is displayed: "cannot invoke "String.toCharArray()" because "<parameter1>" is null".

A Demo that reproduces the problem
[example-maven-plugin.zip](https://github.com/FasterXML/jackson-dataformats-text/files/10773532/example-maven-plugin.zip)

**Comment by cowtowncoder** [comment] 2023-02-20 00:40
I do not understand what the problem might be from description; and included package fails to build.
Class included does not seem to refer to Jackson YAML module at all.

Note that actual reproduction should not rely on external libraries or frameworks as that does not allow isolating whatever the problem in module is.

**Comment by cowtowncoder** [comment] 2023-04-13 03:44
Cannot reproduce, closing.

**Closed by cowtowncoder** 2023-04-13 03:44 UTC
Labels: yaml, need-test-case
