### ISSUE TITLE
If there is an error in the input  execution terminates

### ISSUE THREAD

**Issue by digitalrinaldo** [FasterXML/jackson-dataformats-text#38] opened 2017-09-15 17:04 UTC
CSV data  may have a syntax error. The user may wich to continue with the next record.  When using CSV parsing with 
`import com.fasterxml.jackson.dataformat.csv.CsvMapper;
...
it = mapper.readerFor(Map.class).with(schema).readValues(csvFile);
`
it doesn't appear to be able to continue with the next record.

**Comment by cowtowncoder** [comment] 2017-09-15 17:20
@digitalrinaldo Thank you for reporting the problem. However, I would need a bit more information:

1. Which Jackson CSV module version are you using?
2. How do you reproduce this? (kind of input; ideally a small unit test)

I ask this because there is code to try to recover from many kinds of input discrepancies, as of version 2.9(.1) (and late 2.8, like 2.8.10). However, it is impossible to guarantee recovery from any and all problems, so we need to tackle cases where recovery does not work and see what can be done.

Challenge in handling is two-fold:

- How to catch exception being reported by decoder, and determine if it could be handled
- How to recover from possible inconsistent state (what input to skip etc)

**Comment by digitalrinaldo** [comment] 2017-09-17 17:49
> On Sep 15, 2017, at 1:20 PM, Tatu Saloranta <notifications@github.com> wrote:
> 
> @digitalrinaldo <https://github.com/digitalrinaldo> Thank you for reporting the problem. However, I would need a bit more information:
> 
> Which Jackson CSV module version are you using?
I think it was the latest. 
> How do you reproduce this? (kind of input; ideally a small unit test)

The following happens often for me — there is some error in the csv data and rather than pre process ll the record I would rather keep an exception log.  I can’t see to catch the following exception and get the record and continue.

I can make a small record if needed.  The following should generate the issue

Col1,Col2,Col3
A,b,c
….


AA,,BB,CC
D,E,F
G,H,I
….

**Comment by cowtowncoder** [comment] 2017-09-20 19:20
@digitalrinaldo What I meant was full reproduction, with setup you are using (POJO to bind to, if any; `CsvSchema` creteed), along with ensuring you are using a relatively late version (2.8.10 or 2.9.1).
Quite a bit of work has been done to allow recovery so above case seems like it should be handled already. If not, a test is needed.

**Comment by cowtowncoder** [comment] 2017-11-30 05:21
Need a reproduction of the problem to proceed; closing without one. May be reopened with a unit test.

**Closed by cowtowncoder** 2017-11-30 05:21 UTC
