### ISSUE TITLE
`JavaPropsMapper` doesn't close the .properties file properly after reading

### ISSUE THREAD

**Issue by fcolmenarez** [FasterXML/jackson-dataformats-text#179] opened 2020-03-12 16:24 UTC
When I read an object from a .properties file I can't delete the file, access is held by the JVM. The input stream isn't closed properly unlike the regular JSON parser which does close.

This came up in a scenario when we read a properties file to create the object and later needed to delete the file.

Only seems to happen under Windows 10 (Linux is NOT impacted). Java version is 8 using Open JDK 8 u242 b08. 

Attached a zip file with a small maven project created in IntelliJ demonstrating the issue. Run "compile" to ensure the resources (.json, .properties files) are copied to the target folder before each run. 

[jackson-testing.zip](https://github.com/FasterXML/jackson-dataformats-text/files/4325288/jackson-testing.zip)

**Comment by cowtowncoder** [comment] 2020-03-12 17:53
Thank you for reporting this, providing unit test. Will have a look.

**Comment by cowtowncoder** [comment] 2020-03-12 21:12
Ah. Yes, I can see where this occurs. Just need to figure out best way to handle closing within `JavaPropsParser`, in appropriate cases (since there is special case of `InputStream` being passed, caller requesting stream not to be closed).
Ideally also need to see how to add an automated test case.

**Comment by fcolmenarez** [comment] 2020-03-12 21:25
Glad to be of help. For now we are working around it by loading the properties file separately into a byte array in memory and pass that to the mapper (the files is small enough size is not a concern)

**Comment by cowtowncoder** [comment] 2020-03-12 22:26
Fixed (with test reproduction), to be included in 2.10.4

**Closed** 2020-03-12 22:41 UTC
Labels: 2.10, properties
