### ISSUE TITLE
Exception when attempting to use `ObjectMapper.readValues<T>(parser).readAll()` when parser is pointing to `START_ARRAY`

### ISSUE THREAD

**Issue by egk2374** [FasterXML/jackson-dataformats-text#434] opened 2023-09-29 01:14 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

If parser's current token is START_ARRAY ('[') then attempting to run `objectMapper.readValues<T>(parser).readAll()` with throw an exception. When in this scenario, running parser.nextValue() prior to readValues will execute everything successfully. Until digging through the debugger to inspect these properties, it was not clear that this was the issue and the errors thrown were extremely confusing.

### Version Information

Kotlin 1.9.10
Gradle 7.4.2
jackson 2.14.2

### Reproduction

read in yaml that looks something like
``` yaml
foo:
  - alpha: 3.2
  - beta: 2.221
  - gamma: 1.234
```
Then attempt to run `objectMapper.readValues<Map<String, Double>>(parser).readAll()`. It crashes.
Try again but first run `parser.nextValue()` (or perhaps `if (parser.currentToken.asString() == "[") parser.nextValue()`) and it all parses correctly.

### Expected behavior

I should not need to check for the START_ARRAY character in parser. This type of safety should be implicit to the library.

**Comment by cowtowncoder** [comment] 2023-09-29 23:59
@egk2374 What is the exception being thrown here? Looking at suggested code, assuming I got it right (since there was no exact reproduction included), it would seem that you may have misunderstood intended usage, resulting in mismatch of structure: note that you have document with key `foo` and the interpretation by Jackson here is that you are providing a sequence of main level documents (actually only one in example), all with number values. But this is not true: value of `foo` is Array. That would lead to mismatch.

I assume you were expecting to bind values under `foo`: if so, parser does need to be advanced to point to `START_ARRAY` of that actual value. Except for root-level (where many formats allow a sequence of root values without surrounding array), parser does need to point to `START_ARRAY` for `readValues()` to succeed.

Whether exception is misleading or not is easier to say if you include it in description.

**Comment by egk2374** [comment] 2023-09-30 02:17
I apologize I forgot to include the exact exception message:
```
Cannot deserialize instance of `java.util.LinkedHashMap<java.lang.String,java.lang.Double>` out of START_ARRAY token
```
Some more context: I am deserializing to
```
data class SomeClass(
    @JsonDeserializer(MyDeserializer::class)
    val foo: Map<String, Double>
)

class MyDeserializer : JsonDeserializer<Map<String, Double>>() {
    override fun deserialize(parser: JsonParser?, ctxt: DeserializationContext?): Map<String, T> {
        parser?.let {
            // if (parser.currentToken.asString() == "[") parser.nextToken() // will fail with this line commented
            val values = objectMapper.readValues<Map<String, Double>>(parser).readAll()
            // fold list
        } ?: throw Exception("null parser")
    }
}
```
Thus at the time of entering the deserialize function, parser contains the tokens `[{"alpha": 3.2}, {"beta": 2.221}, {"gamma": 1.234}]` in other words, an array of maps or List<Map<String, Double>> which is precisely the return type from readAll()

**Comment by cowtowncoder** [comment] 2023-09-30 04:19
Oh. Ok yeah this is not supported usage: deserializers should not try to use `ObjectMapper`s method for their parsing -- that may or may not work but is not guaranteed to handle same cases as if used "from outside".
Instead, deserializers are to either use `JsonParser` methods directly, call methods `DeserializationContext` exposes, or delegate to other `JsonDeserializer`s (possibly via `DeserializationContext`).
`ObjectMapper` methods will do setup that does not work well with `JsonDeserializer` delegation.

Since this is not supported usage, I can't really help further with the specific code. But you may be able to see if you can use processing similar to what `readValues()` does: it will delegate to element value `JsonDeserializer`s; and there are methods in `DeserializationContext` for reading individual values (and actually `List`s etc if you want).

**Comment by cowtowncoder** [comment] 2023-10-19 03:31
Usage not supported: custom deserializers are not expected to call `ObjectMapper` (they will not have access to one that creates them, and that is intentional).
Closing.

**Closed by cowtowncoder** 2023-10-19 03:31 UTC
Labels: yaml
