### ISSUE TITLE
Jackson 2.9.5, 2.9.6 incompatible with snakeyaml 1.20, 1.21

### ISSUE THREAD

**Issue by yborovikov** [FasterXML/jackson-dataformats-text#81] opened 2018-04-25 20:28 UTC
A backwards-incompatible (with jackson `2.9.5`) change was [introduced](https://bitbucket.org/asomov/snakeyaml/commits/6cb855839ebc1f3796cff26aa6e5423f1395b975) in snakeyaml `1.20`, so anyone trying to use the latest released versions of jackson and snakeyaml would run into a problem:
```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.events.MappingStartEvent.<init>(Ljava/lang/String;Ljava/lang/String;ZLorg/yaml/snakeyaml/error/Mark;Lorg/yaml/snakeyaml/error/Mark;Ljava/lang/Boolean;)V

    at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.writeStartObject(YAMLGenerator.java:489)
    at com.fasterxml.jackson.core.base.GeneratorBase.writeStartObject(GeneratorBase.java:286)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:626)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207)
```

**Comment by Dico200** [comment] 2018-07-26 20:33
Running into the same issue.

**Comment by cowtowncoder** [comment] 2018-07-26 21:49
@Dico200 and you did check with `2.9.6` which has been out for while now?

**Comment by cthiebaud** [comment] 2018-07-30 13:03
@cowtowncoder the issue is still open with 2.9.6

**Comment by Dico200** [comment] 2018-08-02 13:35
Yes, 2.9.6

**Comment by Dico200** [comment] 2018-08-02 13:37
I resolved my problem. I found more transitive dependencies for snakeyaml that were overriding the version. But snakeyaml making this unnecessary breaking change isn't appreciated, for sure. I didn't see any warnings for it, and the version bump is similar to any other.

**Comment by ahgittin** [comment] 2018-08-15 17:03
I have opened https://bitbucket.org/asomov/snakeyaml/issues/412/restore-the-boolean-constructors-for to try to facilitate this.  I've seen this error in other projects too.  No fun!

**Comment by ahgittin** [comment] 2018-08-20 14:09
Once snakeyaml 1.22 is out this problem should go away so long as versions 1.20/1.21 are avoided.

**Comment by Sufod** [comment] 2018-08-21 09:31
Same issue here :(

**Comment by cthiebaud** [comment] 2018-08-28 10:27
I confirm the issue is fixed with snakeyaml 1.23

**Comment by yborovikov** [comment] 2018-08-28 15:16
Awesome, I'll close #82 now, and this one once snakeyaml 1.23 is [released](https://mvnrepository.com/artifact/org.yaml/snakeyaml).

**Comment by soberich** [comment] 2018-08-30 13:31
@yborovikov  Man, thanks a lot, I was have to repackage `jackson-dataformats` for that purpose only
and raised a relevant issue https://github.com/swagger-api/swagger-core/issues/2925
thank you for that PR

**Comment by cthiebaud** [comment] 2018-08-30 14:13
FYI, snakeyaml 1.23 is released since 2018-08-27, cf.

https://search.maven.org/artifact/org.yaml/snakeyaml

or 

https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.23/

**Closed** 2018-08-31 20:42 UTC
Labels: yaml
