### ISSUE TITLE
YAML Mapper not quoting `#` in cases where it should

### ISSUE THREAD

**Issue by MelleD** [FasterXML/jackson-dataformats-text#492] opened 2024-08-20 15:27 UTC
If I put a path in front of a hashtag, the Quotes is deleted every time. If there is nothing in front of the hashtag, the quotes are retained

This happens only with the feature `YAMLGenerator.Feature.MINIMIZE_QUOTES`

Example

` String yaml =  new YAMLMapper().enable( YAMLGenerator.Feature.MINIMIZE_QUOTES ).writeValueAsString( json );`

Path is `"#/components/responses/ClientError"`

Out come is
```
      responses:
        "400":
          $ref: "#/components/responses/ClientError"
```

If I put something in front of the hashtag the " are deleted
Path is `"core-api.yaml#/components/responses/ClientError"`

Out come is which is invalid in open api. I would also expect the "
```
      responses:
        "400":
          $ref: core-api.yaml#/components/responses/ClientError
```

I this a bug or currently intended with the `YAMLGenerator.Feature.MINIMIZE_QUOTES `?

**Comment by cowtowncoder** [comment] 2024-08-20 21:14
Which version?

**Comment by MelleD** [comment] 2024-08-21 06:02
The problem is that I write an openapi file and there should be quotation in the ref.

References are referenced using the hashtag
https://swagger.io/docs/specification/using-ref/

With local references everything works, but with remote references that are in another file, the " are then deleted and the reference is therefore not valid.

Version is 2.17.2

**Comment by cowtowncoder** [comment] 2024-08-21 18:11
@MelleD would you able to provide test code to show the issue? It sounds like `#` can be interpreted as comment even in cases where non-space characters precede it; if so, I'd like to address the problem.

**Comment by MelleD** [comment] 2024-08-22 07:49
Yes sure:

Here is an small open api example in JSON

```
{
  "openapi": "3.0.3",
  "info": {
    "title": "Test",
    "version": "v1.0.0"
  },
  "servers": [
    {
      "url": "https://test.example.com/api/v1.0.0",
      "variables": {
        "api-version": {
          "default": "v1.0.0"
        }
      }
    }
  ],
  "paths": {
    "/my-test/{test-Id}": {
      "get": {
        "parameters": [
          {
            "name": "test-Id",
            "in": "path",
            "description": "The ID of sth.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/Test"
          },
          "400": {
            "$ref": "core-api.yaml#/components/responses/ClientError"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Test": {
        "description": "This is a test.",
        "type": "object",
        "properties": {}
      }
    },
    "responses": {
      "Test": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Test"
            }
          }
        },
        "description": "The request was successful."
      }
    }
  }
}

```

You see the critical point is the 400 status code with the reference. I read the json and would like to convert it to YAML


Test case:

```
   @Test
   void testYamlGenerator() throws IOException {
      final String json = "{\n"
            + "  \"openapi\": \"3.0.3\",\n"
            + "  \"info\": {\n"
            + "    \"title\": \"Test\",\n"
            + "    \"version\": \"v1.0.0\"\n"
            + "  },\n"
            + "  \"servers\": [\n"
            + "    {\n"
            + "      \"url\": \"https://test.example.com/api/v1.0.0\",\n"
            + "      \"variables\": {\n"
            + "        \"api-version\": {\n"
            + "          \"default\": \"v1.0.0\"\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"paths\": {\n"
            + "    \"/my-test/{test-Id}\": {\n"
            + "      \"get\": {\n"
            + "        \"parameters\": [\n"
            + "          {\n"
            + "            \"name\": \"test-Id\",\n"
            + "            \"in\": \"path\",\n"
            + "            \"description\": \"The ID of sth.\",\n"
            + "            \"required\": true,\n"
            + "            \"schema\": {\n"
            + "              \"type\": \"string\"\n"
            + "            }\n"
            + "          }\n"
            + "        ],\n"
            + "        \"responses\": {\n"
            + "          \"200\": {\n"
            + "            \"$ref\": \"#/components/responses/Test\"\n"
            + "          },\n"
            + "          \"400\": {\n"
            + "            \"$ref\": \"core-api.yaml#/components/responses/ClientError\"\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"components\": {\n"
            + "    \"schemas\": {\n"
            + "      \"Test\": {\n"
            + "        \"description\": \"This is a test.\",\n"
            + "        \"type\": \"object\",\n"
            + "        \"properties\": {}\n"
            + "      }\n"
            + "    },\n"
            + "    \"responses\": {\n"
            + "      \"Test\": {\n"
            + "        \"content\": {\n"
            + "          \"application/json\": {\n"
            + "            \"schema\": {\n"
            + "              \"$ref\": \"#/components/schemas/Test\"\n"
            + "            }\n"
            + "          }\n"
            + "        },\n"
            + "        \"description\": \"The request was successful.\"\n"
            + "      }\n"
            + "    }\n"
            + "  }\n"
            + "}\n";
      final YAMLMapper yamlMapper = new YAMLMapper( ).enable( YAMLGenerator.Feature.MINIMIZE_QUOTES );

      System.out.println( yamlMapper.writeValueAsString( objectMapper.readTree(json) ) );
   }
```
Outcome is:

```
openapi: 3.0.3
info:
  title: Test
  version: v1.0.0
servers:
- url: https://test.example.com/api/v1.0.0
  variables:
    api-version:
      default: v1.0.0
paths:
  /my-test/{test-Id}:
    get:
      parameters:
      - name: test-Id
        in: path
        description: The ID of sth.
        required: true
        schema:
          type: string
      responses:
        "200":
          $ref: "#/components/responses/Test"
        "400":
          $ref: core-api.yaml#/components/responses/ClientError
components:
  schemas:
    Test:
      description: This is a test.
      type: object
      properties: {}
  responses:
    Test:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Test"
      description: The request was successful.
```

You see on 400 there are the missing quotes



With the YAMLFactory and this class is working, but not sure if this a general rule or is this related to the open api spec with the hashtag reference see: https://swagger.io/docs/specification/using-ref/

```
  private static class OpenApiStringQuotingChecker extends StringQuotingChecker.Default {

      @Override
      protected boolean valueHasQuotableChar( final String inputStr ) {
         if ( inputStr.contains( "#" ) ) {
            return true;
         }
         return super.valueHasQuotableChar( inputStr );
      }
   }

```

Maybe a solution is to create a new feature flag for OPEN_API

```
openapi: 3.0.3
info:
  title: Test
  version: v1.0.0
servers:
- url: https://test.example.com/api/v1.0.0
  variables:
    api-version:
      default: v1.0.0
paths:
  /my-test/{test-Id}:
    get:
      parameters:
      - name: test-Id
        in: path
        description: The ID of sth.
        required: true
        schema:
          type: string
      responses:
        "200":
          $ref: "#/components/responses/Test"
        "400":
          $ref: "core-api.yaml#/components/responses/ClientError"
components:
  schemas:
    Test:
      description: This is a test.
      type: object
      properties: {}
  responses:
    Test:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Test"
      description: The request was successful.
```

**Comment by cowtowncoder** [comment] 2024-08-22 16:32
I am sorry -- I meant a smaller self-contained test case. Not an in-detail manual explanation.

**Comment by cowtowncoder** [comment] 2024-08-22 16:33
(re-worded title based on my high-level understanding)

**Comment by MelleD** [comment] 2024-08-22 17:47
He? Just execute the unit test and you see the issue? What is smaller than a unit test?

**Comment by cowtowncoder** [comment] 2024-08-22 19:00
Uh oh. Sorry. I missed the obvious one -- you did include it. N/m. :)

**Comment by MelleD** [comment] 2024-08-22 20:48
@cowtowncoder ok :)

**Comment by cowtowncoder** [comment] 2024-08-22 22:46
@MelleD much appreciated: and just to make sure, I don't mind explanations that complement reproduction. But occasionally I get only explanations so I ... jumped to conclusions here.
Apologies for that again.

**Comment by cowtowncoder** [comment] 2024-08-22 22:50
@MelleD One more thing tho: I can see missing quotes (as per functionality) -- but is the actual problem that trying to re-read generated YAML will be missing content after `#`?

I mean, not having quotes is intentional if BUT ONLY IF it does not result in problems parsing resulting YAML.

**Comment by cowtowncoder** [comment] 2024-08-23 03:11
Ok. After adding a simple test for round-tripping, it looks like there IS NOT actual loss of content -- String value is retained and `#` is not taken to mean comment.
So this is only about cosmetic part of not retaining double-quotes; and as per #465 `MINIMIZE_QUOTES` will try to minimize amount of quotes.
Because of this, I think things are actually working as expected.
(took me a while to get there :) )

Now: if you do want to force quoting in this case, the use of custom `StringQuotingChecker` seems like the right way to go: that way you have full control over quoting details.

Closing; may be re-opened if I misunderstood something, or new problems surface.

**Closed by cowtowncoder** 2024-08-23 03:11 UTC
Labels: yaml

**Comment by MelleD** [comment] 2024-08-23 06:50
How I said before for open api it’s **not** cosmetic. It is an semantic error see description.

**Comment by cowtowncoder** [comment] 2024-08-23 14:07
@MelleD That is semantically equivalent: quoting is optional.

If not, please show how is it different via deserialized content differing. Usage via Open API in itself is irrelevant, what matters is logical content, not physical encoding.

**Comment by MelleD** [comment] 2024-08-23 14:39
Also possible that the Editor have an bug

**Comment by cowtowncoder** [comment] 2024-08-24 03:19
@MelleD yes, that sounds plausible. I would suggest you use the custom `StringQuotingChecker` to enforce quoting -- if it's needed, it's needed. For this specific case.
