### ISSUE TITLE
SequenceWriter doesn't work depending on the order of items in a list: CSV generator does not support Object values for properties (nested Objects)

### ISSUE THREAD

**Issue by Davidixxus** [FasterXML/jackson-dataformats-text#194] opened 2020-04-16 15:58 UTC
Hi, people. 
I have found a weird behaviour of SequenceWriter when it's used within a loop of a list. 
This is the code to reproduce the issue 

```java
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import com.fasterxml.jackson.databind.SequenceWriter;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;

public class Tests {

    private final List<String> headers = Arrays.asList(
            "sourceId");

    public Tests() throws IOException {
        CsvSchema.Builder csvSchemaBuilder = CsvSchema.builder();
        headers.forEach(csvSchemaBuilder::addColumn);
        CsvSchema csvSchema = csvSchemaBuilder.build().withHeader();
        Path csvPath = Files.createTempFile("csv", "temporaryFile");
        String pathCsvFile = csvPath.toFile().getAbsolutePath();
        CsvMapper csvMapper = new CsvMapper();
        ObjectMapper mapper = new ObjectMapper();
        List<JsonNode> listMessages = new ArrayList<>();
        final String jsonNode1 = "{\"donotexist\":\"donotexist\",\"sourceId\":\"\"}";
        final String jsonNode2 = "{\"sourceId\":\"\"}";
        listMessages
                .add(mapper.readTree(jsonNode1));
        listMessages
                .add(mapper.readTree(jsonNode2));

        try (FileWriter out = new FileWriter(pathCsvFile, true)) {
            ObjectWriter objectWriter = csvMapper.writerFor(JsonNode.class);
            objectWriter.getFactory().disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET);

            try (SequenceWriter sequenceWriter = objectWriter.with(csvSchema).writeValues(out)) {
                for (int i = 0, len = listMessages.size(); i < len; ++i) {
                    methodToTrigger(sequenceWriter, listMessages, i);

                }
            }
        }

    }

    private void methodToTrigger(SequenceWriter sequenceWriter, List<JsonNode> listMessages, int index) {
        try {
            sequenceWriter.write(listMessages.get(index));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        try {
            new Tests();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

The code is quite simple and it doesn't work. However, if I change the code to change the order of elements in the list, so: 

```
 listMessages
                .add(mapper.readTree(jsonNode2));
 listMessages
                .add(mapper.readTree(jsonNode1));
```

instead of 

```       
 listMessages
                .add(mapper.readTree(jsonNode1));
        listMessages
                .add(mapper.readTree(jsonNode2));
```

The code works like a charm. 
The error thrown by the app is "CSV generator does not support Object values for properties (nested Objects)"

**Comment by cowtowncoder** [comment] 2020-04-16 16:35
Interesting. Sounds like a bug.

Which Jackson version is this with?

**Comment by Davidixxus** [comment] 2020-04-16 16:59
Wow, the version, of course. Sorry, I forgot to write it. The bug  is happening in version 2.9.4 and version 2.6.7.

**Comment by cowtowncoder** [comment] 2020-04-16 17:35
Ok no prob. Would it be easy to just quickly check with 2.10.3 as well? (if not, I can check it when I have time to look into it).

**Comment by cowtowncoder** [comment] 2020-04-17 03:58
Ok, so, I am testing this against 2.11.0.rc1 with slightly modified test and  get exception:

```
com.fasterxml.jackson.dataformat.csv.CsvMappingException: Unrecognized column 'donotexist': known columns: ["sourceId"]
	at com.fasterxml.jackson.dataformat.csv.CsvMappingException.from(CsvMappingException.java:32)
```

which makes sense: schema does not column for `donotexist`.
Note that your test swallows exception: this is possible to do but in that case underlying `SequenceWriter` and or `CsvGenerator` are not guaranteed to be in stable state -- operation should not continue, and behavior is undefined.
However, if you would want to ignore any property for which no column exists, you can enable `JsonGenerator.Feature.IGNORE_UNKNOWN`.
Doing that will quietly just ignore attempted writes of such values and "just works".

Now, I am not quite sure why you get different exception: it could be something fixed in 2.10.x.
But I think you will also want to ignore unknown values (unmappable).

**Comment by Davidixxus** [comment] 2020-04-17 05:42
Hey, good morning.
Yes, that exception is ok. 
However, what's worrying me a bit is that the code fails when I have more than one "object" to process and if one of them fails, the subsequent objects will fail too (even when they are correct)
I can't upgrade to that version, so I'll go with the workaround for now.

**Comment by Davidixxus** [comment] 2020-04-17 11:45
BTW, I'm getting two exceptions: one for the "column doesn't exist" and another one for "CSV generator does not support Object values for properties (nested Objects)"

**Comment by cowtowncoder** [comment] 2020-04-17 17:10
@Davidixxus first of all, thank you for quick follow up!

On exception if you get an exception, state of the system is not guaranteed to remain intact: this is something that you simply can not count on. Failure means processing can not continue, unless specific component explicitly specifies it is safe to continue its usage. In this example, error occurs within writing of an "Object", leaving out closing "End object" marker. Part of this is due to separate of format-agnostic databind (jackson-databind has no knowledge of underlying format) and formatting backend (which in this case notices mapping from logical name to index position is missing).
So that part is working as designed -- you will need to avoid problem, not continue on in case of that problem.

One specific exception to this is CSV side of `MappingIterator` (created with `ObjectReader.readValues()`): it will try to recover parser state after some mapping problems.
In theory something similar could perhaps be attempted on writer side, but it may not be very easy to implement reliably and -- more importantly -- does seem quite as urgent as on reader side because whereas input varies more and calling code often has less control over it, writing side is usually directly controlled by code.
Having said that, if something relatively simple can be devised to try either give better error information, or keep state handling more intact, I am always open to improvements.

That aside: when you configure things to ignore unknown columns on writer side, and upgrade to 2.10.3, things should work better. In that case test passed for me at least.
If not, I would be interested in remaining issues -- especially as I am finalizing 2.11.0 release and hope to close as many dangling issues as possible.

**Comment by Davidixxus** [comment] 2020-04-20 14:11
Hi, @cowtowncoder; thanks for your reply and your help, your explanation has confirmed what I was thinking by reading the code, many thanks again. 
I can't upgrade to that version so far, but simply ignoring the errors works like a charm for my scenario. 
As soon as I test this with an updated version. I'll let you know.
Thanks, you can close this ticket :)

**Comment by cowtowncoder** [comment] 2020-04-20 16:20
@Davidixxus Ok good!

**Closed by cowtowncoder** 2020-04-20 16:20 UTC
Labels: csv
