### ISSUE TITLE
[Yaml] [Suggestion] Ability to add comments

### ISSUE THREAD

**Issue by PeachesMLG** [FasterXML/jackson-dataformats-text#269] opened 2021-05-08 11:42 UTC
Not sure if this is the right place to ask, and appologies if this is already possible.

Would be cool if we could annotate fields with like @YamlComment(comment = "The yaml comment here") to add a comment to the file

Not sure how hard this would be, im too dumb to understand this codebase, but I think it would be a cool idea :)

**Comment by yawkat** [comment] 2021-05-08 14:03
At the moment, jackson-databind has no machinery to pass on format-specific information like this. Also see #36 for yaml, and #254 for toml.

**Comment by cowtowncoder** [comment] 2021-05-08 19:00
Right, there are at least these problems:

1. There is no generic comment writing functionality (databinding is format-agnostic and must stick to using methods common to all backends). YAML, XML, Properties have comments at least (and JSON arguably with non-standard features enabled)
2. Even if there was, figuring out location for comments is tricky: where should it end? (before key/value, after, in-between?) Adding comment in some place would be more doable, but users probably want more control than is easy to provide.

**Comment by cowtowncoder** [comment] 2022-06-26 22:16
One thing I forgot to note is that use of `@JsonRawValue` annotation might work, to some degree. It allows injecting any String as a value. I am not saying it provides what is asked here but just that it could work for some usage.

**Comment by big-andy-coates** [comment] 2024-07-17 10:33
@cowtowncoder - this issue can be closed as a duplicate of https://github.com/FasterXML/jackson-dataformats-text/issues/36, if you're so inclined. :)

**Comment by cowtowncoder** [comment] 2024-07-17 15:28
Ah yes; will do so.

**Closed by cowtowncoder** 2024-07-17 15:28 UTC
Labels: yaml
